stages:

- stage: __default

  jobs:

  - job: Job

    pool:

      name: 'Default'

    steps:

    - task: DownloadBuildArtifacts@0

      displayName: 'Download Build Artifacts'

      inputs:

        buildType: 'specific'

        project: 'DotNet_Pipeline'

        pipeline: 'Build-faraz9993.netapp'

        buildVersionToDownload: 'latest'

        downloadPath: '$(Pipeline.Workspace)'

        artifactName: 'netapplication'

    - task: AzureFunctionApp@1

      displayName: 'Release Live discounts Func'

      inputs:

        azureSubscription: faraz-svc

        appType: functionApp

        appName: 'FarazFunctionApp'

        package: '$(Pipeline.Workspace)/netapplication/*.zip'

        deploymentMethod: 'runFromPackage'

    - task: AzureFunctionApp@2

      displayName: 'Release Func'

      inputs:

        connectedServiceNameARM: faraz-svc

        appType: functionApp

        appName: 'FarazFunctionApp'

        package: '$(Pipeline.Workspace)/netapplication/*.zip'

        deploymentMethod: 'runFromPackage'

    - task: AzureWebApp@1

      displayName: 'Deploy to Azure Web App'

      inputs:

        azureSubscription: faraz-svc

        appName: 'FarazWebApp'

        appType: webApp

        package: '$(Pipeline.Workspace)/netapplication/*.zip'

        deploymentMethod: 'auto'