name: Dev Workflow

on:
  push:
    branches: ["dev", "release"]
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore netapplication.csproj

      - name: Build the application
        run: dotnet build netapplication.csproj --configuration Release

      # - name: Run the application
      #   run: dotnet run

      - name: Pack the NuGet package
        run: |
          VERSION=${{ github.ref_name }}
          dotnet pack netapplication.csproj --configuration Release --version-suffix $VERSION --output ./output       
    
      - name: List contents of output directory
        run: |
             ls -l ./output

      - name: Push to Nuget-tag Repository of Nexus 
#        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/main' }}
        env:
          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
        run: |
          cd ./output
          mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
          ls -l
          dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY

      - name: Push to Nuget-snapshot Repository of Nexus          
        if: ${{ github.ref_name == 'dev' }}
        env:
          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-snapshot/
        run: |
          BRANCH_NAME=$(git branch --contains $(git rev-parse HEAD) | grep -Eo 'dev')
          if [[ "${GITHUB_REF}" == refs/tags/* && $BRANCH_NAME !=' dev' ]]; then
            cd ./output
            mv netapplication.1.0.0.nupkg netapplication.${{ github.ref_name }}-${{ github.job }}.nupkg
            dotnet nuget push netapplication.${{ github.ref_name }}-${{ github.job }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
          else
            echo "It is a tag so skipping."
          fi
          
      
      - name: Pushing to Nuget-rc Repository of Nexus      
        if: ${{ github.ref_name == 'release' }}
        env:
          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-rc/
        run: |
          cd ./output
          COMMIT_SHA=${{ github.sha }}
          SHORT_SHA=${COMMIT_SHA:0:6}  # Extract first 6 characters of commit SHA
          mv netapplication.1.0.0.nupkg netapplication.${{ github.ref_name }}-${SHORT_SHA}.nupkg
          dotnet nuget push netapplication.${{ github.ref_name }}-${SHORT_SHA}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
