name: Main Workflow

on:
  push:
    branches: ["dev", "release"]
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore netapplication.csproj

      - name: Build the application
        run: dotnet build netapplication.csproj --configuration Release

      - name: Run the application
        run: dotnet run

 #     - name: Pack the application for "nupkg"
 #       run: dotnet pack netapplication.csproj --configuration Release --output ./output

      - name: Pack the NuGet package
        run: |
          VERSION=${{ github.ref_name }}
          dotnet pack netapplication.csproj --configuration Release --version-suffix $VERSION --output ./output       

    #   - name: Publish the application for "dll"
    #     run: dotnet publish --configuration Release --output ./output --no-build --self-contained falset
    
      - name: List contents of output directory
        run: |
             ls -l ./output 
             

      - name: Push to Nuget-snapshot Repository of Nexus
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-snapshot/
        run: |
          cd ./output
          mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}-${{ github.job }}.nupkg
          ls -l ./output
          dotnet nuget push ./output/*.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
      
      - name: Push to Nuget-rc Repository of Nexus
        if: ${{ github.ref == 'refs/heads/release' }}
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-rc/
        run: |
          cd ./output
          mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}-${{ github.sha }}.nupkg
          ls -l ./output
          dotnet nuget push ./output/*.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
  
      - name: Push to Nuget-tag Repository of Nexus
#        if: github.ref_name == 'main'
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/

        run: |
          cd ./output
          mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
          ls -l ./output
          dotnet nuget push ./output/netapplication.$VERSION.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY