name: .NET Core CI-2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore netapplication.csproj

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test

      - name: Run the application
        run: dotnet run
      
      - name: Pack the application for nupkg
        run: dotnet pack --configuration Release --output ./output

    #   - name: Publish the application for dll
    #     run: dotnet publish --configuration Release --output ./output --no-build --self-contained false
    
      - name: List contents of output directory
        run: ls -l ./output
          
  
      - name: Push to Nexus Repository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
          NEXUS_SOURCE: http://40.90.168.101:8081/repository/faraz_repo/
        run: |
          dotnet nuget push ./output/*.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY 
          
      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ${{ env.ARTIFACT_PATH }}
      
      - name: Download Package Artifact
        uses: actions/download-artifact@v3 
        with:
          name: nuget-package
          path: ./bin/Release



    #   - name: Upload DLL as Artifact
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: netapplication-dll
    #       path: ./output/netapplication.dll
